/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/queue.h File Reference
#include `rtdal_types.h`
*
Data Structures
struct queue_t
Functions
void queue_init (queue_t *q, int pkt_sz, int nof_pkts)
void queue_free (queue_t *q)
int queue_is_empty (queue_t *q)
int queue_is_full (queue_t *q)
h_pkt_t * queue_request (queue_t *q)
int queue_push (queue_t *q)
h_pkt_t * queue_pop (queue_t *q, int tstamp)
int queue_release (queue_t *q)
Function Documentation
void queue_free (queue_t * q)
Definition at line 39 of file queue.c.
References queue_t::data, and queue_t::packets.
Referenced by rtdal_itfqueue_remove().
void queue_init (queue_t * q, int pkt_sz, int nof_pkts)
Definition at line 25 of file queue.c.
References queue_t::data, h_pkt_t::data, queue_t::packets, queue_t::read, queue_t::size, h_pkt_t::valid, and queue_t::write.
Referenced by rtdal_itfqueue_init().
int queue_is_empty (queue_t * q) [inline]
Definition at line 50 of file queue.c.
References queue_t::packets, queue_t::read, and h_pkt_t::valid.
Referenced by queue_pop().
int queue_is_full (queue_t * q) [inline]
Definition at line 54 of file queue.c.
References queue_t::packets, h_pkt_t::valid, and queue_t::write.
Referenced by queue_request().
h_pkt_t* queue_pop (queue_t * q, int tstamp)
Definition at line 73 of file queue.c.
References queue_t::packets, qdebug, queue_is_empty(), queue_t::read, and h_pkt_t::tstamp.
Referenced by rtdal_itfqueue_get_pkt().
int queue_push (queue_t * q)
Definition at line 66 of file queue.c.
References queue_t::packets, qdebug, queue_t::size, h_pkt_t::tstamp, h_pkt_t::valid, and queue_t::write.
Referenced by rtdal_itfqueue_put_pkt().
int queue_release (queue_t * q)
Definition at line 93 of file queue.c.
References queue_t::packets, qdebug, queue_t::read, queue_t::size, h_pkt_t::tstamp, and h_pkt_t::valid.
Referenced by rtdal_itfqueue_release_pkt().
h_pkt_t* queue_request (queue_t * q)
Definition at line 58 of file queue.c.
References queue_t::packets, qdebug, queue_is_full(), h_pkt_t::tstamp, and queue_t::write.
Referenced by rtdal_itfqueue_request_pkt().