/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_context.h File Reference
#include <pthread.h>
*
#include `rtdal_itfspscq.h`
*
#include `rtdal_itfphysic.h`
*
#include `rtdal_dac.h`
*
#include `rtdal_machine.h`
*
#include `rtdal_error.h`
*
#include `rtdal_periodic.h`
*
#include `rtdal_time.h`
*
#include `pipeline.h`
*
#include `objects_max.h`
*
#include `rtdal.h`
*
Data Structures
struct rtdal_context_t
Functions
int rtdal_initialize_node (rtdal_context_t *context, string config_file, void(*ts_begin_fnc)(void))
Function Documentation
int rtdal_initialize_node (rtdal_context_t * _context, string config_file, void(*)(void) ts_begin_fnc)
Must be called before any other function.
1) Parse configuration file and fill +machine attributes 2) Create interfaces. Call -createNodeInterfaces() 3) Setup synchronization:   3.1) If I am the synchronization master, set machine.clockSource=CLOCKSRC_TIMER if source=`timer` or machine.clockSource=CLOCKSRC_DAC if source=`dac:/`   3.2) If I am an slave node, set machine.clockSource=CLOCKSRC_TIMER if continuous_mode=FALSE or machine.clockSource=CLOCKSRC_SYNC if continuous_mode=TRUE   3.3) Set machine.syncContinuous boolean if continuous_mode=TRUE   3.4) Set machine.syncMaster boolean if I am the synchronization master reference   3.5) Set machine.syncPeriod to the synchronization period 4) setup DAC (if my node has a DAC). For each DAC, create an instance of the DAC type and:   4.1) Call DAC.openDAC(address,options,null) if machine.clockSource!=CLOCKSRC_DAC   4.2) Call DAC.setScheduler(tsBeginFnc, machine.kernelPrio) if machine.clockSource==CLOCKSRC_DAC 5) create max_spscqs_x_node +spscqs and max_modules_x_node +procs objects
Definition at line 62 of file rtdal_base.c.
References rtdal_context_t::error, rtdal_context_t::machine, rtdal_error_set_context(), rtdal_time_reset(), rtdal_time_set_context(), rtdal_context_t::time, rtdal_time_t::ts_len_us, and rtdal_machine_t::ts_len_us.