/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_time.h File Reference
#include `rtdal_types.h`
*
#include `defs.h`
*
Data Structures
struct rtdal_time_t
Functions
void rtdal_time_set_context (rtdal_time_t *_context)
void rtdal_time_ts_inc ()
int rtdal_time_reset ()
int rtdal_time_reset_realtime (struct timespec *x)
Function Documentation
int rtdal_time_reset ()
Definition at line 40 of file rtdal_time.c.
References rtdal_time_t::init_time, RTDAL_SYSERROR, and rtdal_time_t::ts_counter.
Referenced by rtdal_initialize_node().
int rtdal_time_reset_realtime (struct timespec * x)
Definition at line 56 of file rtdal_time.c.
References rtdal_time_t::init_time, and rtdal_time_t::ts_counter.
Referenced by pipeline_run_from_timer().
void rtdal_time_set_context (rtdal_time_t * _context)
Sets the rtdal context pointer
Parameters
_context
Definition at line 35 of file rtdal_time.c.
Referenced by rtdal_initialize_node().
void rtdal_time_ts_inc () [inline]
Definition at line 65 of file rtdal_time.c.
References rtdal_time_t::ts_counter.
Referenced by kernel_tslot_run().