/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_task.h File Reference
#include <pthread.h>
*
#include `rtdal.h`
*
Macros
#define TASK_DEFAULT_PRIORITY 10
#define TASK_DEFAULT_CPUID -1
Enumerations
enum rtdal_task_type { DETACHABLE,
JOINABLE
 }
Functions
int rtdal_task_new_thread (pthread_t *thread, void *(*fnc)(void *), void *arg, enum rtdal_task_type type, int prio, int cpu, int unblock_signals)
int rtdal_task_new_prio (r_task_t *task, void *(*fnc)(void *), void *arg, int prio, int cpu)
Macro Definition Documentation
#define TASK_DEFAULT_CPUID -1
Definition at line 23 of file rtdal_task.h.
Referenced by rtdal_task_new().
#define TASK_DEFAULT_PRIORITY 10
Definition at line 22 of file rtdal_task.h.
Referenced by rtdal_task_new(), and rtdal_task_new_thread().
Enumeration Type Documentation
enum rtdal_task_type
Enumerator:
DETACHABLE
JOINABLE
Definition at line 28 of file rtdal_task.h.
Function Documentation
int rtdal_task_new_prio (r_task_t * task, void *(*)(void *) fnc, void * arg, int prio, int cpu)
All threads are created with detachable state.
Definition at line 78 of file rtdal_task.c.
References DETACHABLE, JOINABLE, and rtdal_task_new_thread().
Referenced by rtdal_task_new().
int rtdal_task_new_thread (pthread_t * thread, void *(*)(void *) fnc, void * arg, enum rtdal_task_type type, int prio, int cpu, int unblock_signals)
Definition at line 95 of file rtdal_task.c.
References awarn, core_mapping, DETACHABLE, hdebug, nof_cores, RTDAL_ASSERT_PARAM, RTDAL_POSERROR, and TASK_DEFAULT_PRIORITY.
Referenced by kernel_initialize_create_pipeline(), and rtdal_task_new_prio().