/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_base.c File Reference
#include <stddef.h>
*
#include <unistd.h>
*
#include <time.h>
*
#include `defs.h`
*
#include `str.h`
*
#include `rtdal_kernel.h`
*
#include `objects_max.h`
*
#include `rtdal_context.h`
*
#include `rtdal_time.h`
*
#include `rtdal_file.h`
*
#include `rtdal_error.h`
*
#include `rtdal.h`
*
Functions
void rtdal_machine (rtdal_machine_t *machine)
Writes the machine structure into the buffer pointed by *machine.
int rtdal_initialize_node (rtdal_context_t *_context, string config_file, void(*ts_begin_fnc)(void))
int rtdal_start_manager_interfaces (string config_file)
int rtdal_periodic_add (void(*callback)(void), int period)
int rtdal_periodic_remove (void(*callback)(void))
int rtdal_sleep (time_t *t)
sleep the calling thread for the time specified by the time_t structure.
r_itf_t rtdal_itfphysic_get (string name)
r_itf_t rtdal_itfphysic_get_id (int id)
r_itf_t rtdal_itfspscq_new (int max_msg, int max_msg_sz)
r_dac_t rtdal_dac_get (string address)
r_proc_t rtdal_process_new (struct rtdal_process_attr *attr, void *arg)
Variables
int waveforms_notified_failure [MAX_WAVEFORMS]
Function Documentation
int rtdal_initialize_node (rtdal_context_t * _context, string config_file, void(*)(void) ts_begin_fnc)
Must be called before any other function.
1) Parse configuration file and fill +machine attributes 2) Create interfaces. Call -createNodeInterfaces() 3) Setup synchronization:   3.1) If I am the synchronization master, set machine.clockSource=CLOCKSRC_TIMER if source=`timer` or machine.clockSource=CLOCKSRC_DAC if source=`dac:/`   3.2) If I am an slave node, set machine.clockSource=CLOCKSRC_TIMER if continuous_mode=FALSE or machine.clockSource=CLOCKSRC_SYNC if continuous_mode=TRUE   3.3) Set machine.syncContinuous boolean if continuous_mode=TRUE   3.4) Set machine.syncMaster boolean if I am the synchronization master reference   3.5) Set machine.syncPeriod to the synchronization period 4) setup DAC (if my node has a DAC). For each DAC, create an instance of the DAC type and:   4.1) Call DAC.openDAC(address,options,null) if machine.clockSource!=CLOCKSRC_DAC   4.2) Call DAC.setScheduler(tsBeginFnc, machine.kernelPrio) if machine.clockSource==CLOCKSRC_DAC 5) create max_spscqs_x_node +spscqs and max_modules_x_node +procs objects
Definition at line 62 of file rtdal_base.c.
References rtdal_context_t::error, rtdal_context_t::machine, rtdal_error_set_context(), rtdal_time_reset(), rtdal_time_set_context(), rtdal_context_t::time, rtdal_time_t::ts_len_us, and rtdal_machine_t::ts_len_us.
int rtdal_start_manager_interfaces (string config_file)
Configures the control, probe and sync interfaces for the manager 1) For each node, create an interface with name ctrl_nodename 2) For each node, create an interface with name probe_nodename 3) if clockLocal create the sync interface to the sync master, with name `sync`
Definition at line 98 of file rtdal_base.c.
References aerror.
Variable Documentation
int waveforms_notified_failure[MAX_WAVEFORMS]
Definition at line 39 of file pipeline.c.
Referenced by rtdal_process_new().