/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_itfqueue.h File Reference
#include `str.h`
*
#include `rtdal_itf.h`
*
#include `rtdal.h`
*
#include `queue.h`
*
Data Structures
struct rtdal_itfqueue_t
Functions
int rtdal_itfqueue_init (rtdal_itfqueue_t *obj)
int rtdal_itfqueue_create (h_itf_t obj, string address)
int rtdal_itfqueue_remove (h_itf_t obj)
int rtdal_itfqueue_send (h_itf_t obj, void *buffer, int len)
int rtdal_itfqueue_recv (h_itf_t obj, void *buffer, int len)
int rtdal_itfqueue_set_callback (h_itf_t obj, void(*fnc)(void), int prio)
int rtdal_itfqueue_set_blocking (h_itf_t obj, int block)
int rtdal_itfqueue_get_blocking (h_itf_t obj)
h_pkt_t * rtdal_itfqueue_request_pkt (h_itf_t obj)
int rtdal_itfqueue_put_pkt (h_itf_t obj, h_pkt_t *ptr)
h_pkt_t * rtdal_itfqueue_get_pkt (h_itf_t obj)
int rtdal_itfqueue_release_pkt (h_itf_t obj, h_pkt_t *ptr)
int rtdal_itfqueue_set_delay (h_itf_t obj, int delay)
int rtdal_itfqueue_get_delay (h_itf_t obj)
Function Documentation
int rtdal_itfqueue_create (h_itf_t obj, string address)
int rtdal_itfqueue_get_blocking (h_itf_t obj)
Definition at line 120 of file rtdal_itfqueue.c.
References aerror.
int rtdal_itfqueue_get_delay (h_itf_t obj)
Definition at line 184 of file rtdal_itfqueue.c.
References aerror.
h_pkt_t* rtdal_itfqueue_get_pkt (h_itf_t obj)
Definition at line 153 of file rtdal_itfqueue.c.
References rtdal_itfqueue_t::queue, queue_pop(), rtdal_ASSERT_PARAM_P, and rtdal_time_slot().
Referenced by rtdal_itfqueue_recv().
int rtdal_itfqueue_init (rtdal_itfqueue_t * obj)
Definition at line 32 of file rtdal_itfqueue.c.
References queue_t::id, rtdal_itf_t::id, rtdal_itf_t::is_external, rtdal_itfqueue_t::max_msg, rtdal_itfqueue_t::max_msg_sz, rtdal_itfqueue_t::parent, rtdal_itfqueue_t::queue, queue_init(), and rtdal_ASSERT_PARAM.
Referenced by rtdal_itfqueue_new().
int rtdal_itfqueue_put_pkt (h_itf_t obj, h_pkt_t * ptr)
Definition at line 139 of file rtdal_itfqueue.c.
References rtdal_itfqueue_t::queue, queue_push(), rtdal_ASSERT_PARAM, rtdal_ERROR_NOSPACE, rtdal_SETERROR, rtdal_time_slot(), and h_pkt_t::tstamp.
Referenced by rtdal_itfqueue_send().
int rtdal_itfqueue_recv (h_itf_t obj, void * buffer, int len)
Definition at line 87 of file rtdal_itfqueue.c.
References h_pkt_t::data, hdebug, h_pkt_t::len, rtdal_ASSERT_PARAM, rtdal_itfqueue_get_pkt(), and rtdal_itfqueue_release_pkt().
int rtdal_itfqueue_release_pkt (h_itf_t obj, h_pkt_t * ptr)
Definition at line 166 of file rtdal_itfqueue.c.
References aerror, rtdal_itfqueue_t::queue, queue_release(), rtdal_ASSERT_PARAM, rtdal_ERROR_NOSPACE, and rtdal_SETERROR.
Referenced by rtdal_itfqueue_recv().
int rtdal_itfqueue_remove (h_itf_t obj)
Definition at line 44 of file rtdal_itfqueue.c.
References rtdal_itf_t::id, rtdal_itfqueue_t::max_msg, rtdal_itfqueue_t::max_msg_sz, rtdal_itfqueue_t::parent, rtdal_itfqueue_t::queue, queue_free(), and rtdal_ASSERT_PARAM.
h_pkt_t* rtdal_itfqueue_request_pkt (h_itf_t obj)
Definition at line 125 of file rtdal_itfqueue.c.
References aerror, rtdal_itfqueue_t::queue, queue_request(), rtdal_ASSERT_PARAM_P, rtdal_ERROR_NOSPACE, and rtdal_SETERROR.
Referenced by rtdal_itfqueue_send().
int rtdal_itfqueue_send (h_itf_t obj, void * buffer, int len)
Definition at line 55 of file rtdal_itfqueue.c.
References h_pkt_t::data, hdebug, h_pkt_t::len, rtdal_itfqueue_t::max_msg_sz, rtdal_ASSERT_PARAM, rtdal_ERROR_LARGE, rtdal_itfqueue_put_pkt(), rtdal_itfqueue_request_pkt(), and rtdal_SETERROR.
int rtdal_itfqueue_set_blocking (h_itf_t obj, int block)
Definition at line 115 of file rtdal_itfqueue.c.
References aerror.
int rtdal_itfqueue_set_callback (h_itf_t obj, void(*)(void) fnc, int prio)
Definition at line 110 of file rtdal_itfqueue.c.
References aerror.
int rtdal_itfqueue_set_delay (h_itf_t obj, int delay)
Definition at line 179 of file rtdal_itfqueue.c.
References aerror.