Pipeline processes functions
Enumerations
enum rtdal_processerrors_t { FINISH_OK,
RTFAULT,
SIG_RECV,
RUNERROR
 }
Functions
r_proc_t rtdal_process_new (struct rtdal_process_attr *attr, void *arg)
int rtdal_process_remove (r_proc_t proc)
int rtdal_process_run (r_proc_t proc)
int rtdal_process_stop (r_proc_t process)
int rtdal_process_seterror (r_proc_t proc, rtdal_processerrors_t code)
rtdal_processerrors_t rtdal_process_geterror (r_proc_t proc)
int rtdal_process_isrunning (r_proc_t proc)
Detailed Description
Enumeration Type Documentation
enum rtdal_processerrors_t
Enumerator:
FINISH_OK
 The process is running or finished successfully
RTFAULT
 The process missed the defined real-time deadline
SIG_RECV
 The process received a thread-specific signal (SIGSEGV, SIGILL, SIGBUF or SIGFPE)
RUNERROR
 An error occured during process execution. This error is set manually using rtdal_process_seterror()
Definition at line 49 of file rtdal.h.
Function Documentation
rtdal_processerrors_t rtdal_process_geterror (r_proc_t proc)
Definition at line 137 of file rtdal_process.c.
References _rtdal_process_t::finish_code, hdebug, _rtdal_process_t::pid, and RTDAL_ASSERT_PARAM.
int rtdal_process_isrunning (r_proc_t proc)
Definition at line 144 of file rtdal_process.c.
References hdebug, _rtdal_process_t::is_running, _rtdal_process_t::pid, RTDAL_ASSERT_PARAM, and _rtdal_process_t::runnable.
r_proc_t rtdal_process_new (struct rtdal_process_attr * attr, void * arg)
Creates a new process to be executed in one of the kernel pipelines. The structure pointed by attr has the following options:
binary_path: Path to the shared library where the program code resides
pipeline_id: If the machine has more than one pipeline (e.g. in a multi-core system, it indicates to which the process will be loaded).
exec_position: Indicates the execution position in the pipeline.
finish_callback: If non-null, the kernel will call this function when the process finishes (normally or due to an error) its execution.
rtdal_process_new() configures the process parameters and loads it into the pipeline. The process won't execute until a success call to rtdal_process_run() is performed.
The address pointed by arg will be passed to the process as a parameter.
Notes: The shared library must conform with the rtdal_process_t requirements.
Parameters
attr Configures the process attributes
arg Argument to pass to the process each execution cycle
Returns
non-null value on success, zero on error
Definition at line 318 of file rtdal_base.c.
References _rtdal_process_t::arg, _rtdal_process_t::attributes, rtdal_process_attr::exec_position, rtdal_process_attr::finish_callback, _rtdal_process_t::finish_code, FINISH_OK, hdebug, MAX, MAX_WAVEFORMS, rtdal_context_t::mutex, _rtdal_process_t::pid, pipeline_add(), rtdal_process_attr::pipeline_id, pipeline_remove(), rtdal_context_t::pipelines, rtdal_context_t::processes, RTDAL_ASSERT_PARAM_P, RTDAL_ERROR_INVAL, RTDAL_ERROR_NOSPACE, rtdal_process_launch(), RTDAL_SETERROR, rtdal_process_attr::waveform_id, and waveforms_notified_failure.
int rtdal_process_remove (r_proc_t process)
Removes a process from the system, previously loaded using rtdal_process_new(). rtdal_process_remove() removes the process from the allocated pipeline and then unloads the program code from memory. After, if a finish_callback function was provided in the process attributes during rtdal_process_new(), it is now called.
Parameters
obj Pointer to the rtdal_process_t object.
Returns
Zero on success, -1 on error.
1) Call rtdal_pipeline_remove(self->pipeline,self); 2) Call to dlclose(handle) 3) Set pid=0 4) if finishCallback!=null, call the function
Definition at line 73 of file rtdal_process.c.
References _rtdal_process_t::dl_handle, hdebug, _rtdal_process_t::pid, _rtdal_process_t::pipeline, pipeline_remove(), and RTDAL_ASSERT_PARAM.
int rtdal_process_run (r_proc_t process)
Enables the execution of the process identified by the first argument. The process must have been previously loaded using rtdal_process_new().
Parameters
process Handler to the process
Returns
zero on success, -1 on error
Definition at line 107 of file rtdal_process.c.
References hdebug, _rtdal_process_t::pid, RTDAL_ASSERT_PARAM, and _rtdal_process_t::runnable.
int rtdal_process_seterror (r_proc_t proc, rtdal_processerrors_t code)
Definition at line 129 of file rtdal_process.c.
References _rtdal_process_t::finish_code, hdebug, _rtdal_process_t::pid, and RTDAL_ASSERT_PARAM.
Referenced by pipeline_recover_thread().
int rtdal_process_stop (r_proc_t process)
Disables the execution of the process identified by the first argument. The process must have been previously loaded using rtdal_process_new().
Parameters
process Handler to the process
Returns
zero on success, -1 on error
Definition at line 121 of file rtdal_process.c.
References hdebug, _rtdal_process_t::pid, RTDAL_ASSERT_PARAM, and _rtdal_process_t::runnable.