Low-priority task functions
Functions
int rtdal_task_new (r_task_t *task, void *(*fnc)(void *), void *arg)
int rtdal_task_kill (r_task_t task)
int rtdal_task_wait (r_task_t task, void **retval)
int rtdal_task_wait_nb (r_task_t task, void **retval)
void rtdal_task_print_sched ()
Detailed Description
Function Documentation
int rtdal_task_kill (r_task_t task)
Definition at line 42 of file rtdal_task.c.
References RTDAL_POSERROR, and TASK_TERMINATION_SIGNAL.
int rtdal_task_new (r_task_t * task, void *(*)(void *) fnc, void * arg)
Creates a new thread with normal priority, that is, no real-time priority. The thread is detachable, meaning that runs the function pointed by the first parameter and then is destroyed, ignoring the returned value.
Definition at line 38 of file rtdal_task.c.
References rtdal_task_new_prio(), TASK_DEFAULT_CPUID, and TASK_DEFAULT_PRIORITY.
Referenced by main().
void rtdal_task_print_sched ()
Definition at line 189 of file rtdal_task.c.
Referenced by timer_run_thread().
int rtdal_task_wait (r_task_t task, void ** retval)
Definition at line 51 of file rtdal_task.c.
References hdebug, and RTDAL_POSERROR.
int rtdal_task_wait_nb (r_task_t task, void ** retval)
Definition at line 61 of file rtdal_task.c.
References hdebug, and RTDAL_POSERROR.