Time functions
Functions
int rtdal_time_set (time_t *time)
int rtdal_time_get (time_t *time)
int rtdal_time_slot ()
void rtdal_time_interval (time_t *tdata)
int rtdal_time_attach_local ()
Detailed Description
Function Documentation
int rtdal_time_attach_local ()
Called by the manager if obtains the time from shared memory. 1) call shm_open(`/initTime`); and save pointer to init_time. 2) set initTimeShm=TRUE
Definition at line 177 of file rtdal_time.c.
References aerror.
int rtdal_time_get (time_t * time)
Stores the current time in the structure pointed by time pointer.
Definition at line 94 of file rtdal_time.c.
References rtdal_time_t::init_time, RTDAL_ASSERT_PARAM, RTDAL_SYSERROR, and time_t.
Referenced by pipeline_run_from_timer().
void rtdal_time_interval (time_t * tdata)
tdata points to a buffer of 3 time_t consecutive structures. Computes the time interval between position 1 and position 2, storing the result in position 0
Parameters
tdata
Definition at line 127 of file rtdal_time.c.
int rtdal_time_set (time_t * time)
This function is called by syncSlave() in TWO-WAY synchronization mode. It adjusts the local time-slot timer. It has an effect only if clockSource==CLOCKSRC_TIMER
Definition at line 74 of file rtdal_time.c.
References rtdal_time_t::init_time, RTDAL_ASSERT_PARAM, RTDAL_SYSERROR, and time_t.
int rtdal_time_slot ()
returns the time-slot number
Definition at line 115 of file rtdal_time.c.
References rtdal_time_t::ts_counter.
Referenced by kernel_tslot_run(), rtdal_itfspscq_pop(), rtdal_itfspscq_push(), and rtdal_sleep().