/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/pipeline.h File Reference
#include <signal.h>
*
#include `objects_max.h`
*
#include `rtdal_process.h`
*
#include `rtdal_timer.h`
*
Data Structures
struct pipeline_t
Macros
#define PRINT_TIME
Functions
void pipeline_run_from_timer (void *arg, struct timespec *time)
void pipeline_sync_threads ()
void pipeline_initialize (int _num_pipelines)
void * pipeline_run_thread (void *obj)
int pipeline_recover_thread (pipeline_t *obj)
Called from the sigwait kernel thread after a pipeline thread has died. Set the process that caused the fault as non-runnable and create a new pipeline thread.
int pipeline_rt_fault (pipeline_t *obj)
Called when there is an rtfault in the pipeline.
int pipeline_add (pipeline_t *obj, rtdal_process_t *process)
int pipeline_remove (pipeline_t *obj, rtdal_process_t *proc)
Macro Definition Documentation
#define PRINT_TIME
Definition at line 27 of file pipeline.h.
Function Documentation
int pipeline_add (pipeline_t * obj, rtdal_process_t * process)
Adds a process to the pipeline. It is inserted in the position min(n,exec_position) where n is the number of elements in the spscq and exec_position is defined in the process attributes used in the call to rtdal_process_new(). Returns the position it has finally been inserted.
Parameters
obj Pointer to the pipeline_t object where the process is inserted process pointer to the rtdal_process_t object to insert.
Returns
non-negative integer number indicating the position it has been inserted, or -1 on error.
Definition at line 236 of file pipeline.c.
References _rtdal_process_t::attributes, rtdal_process_attr::exec_position, pipeline_t::first_process, hdebug, pipeline_t::id, _rtdal_process_t::next, pipeline_t::nof_processes, _rtdal_process_t::pid, _rtdal_process_t::pipeline, and RTDAL_ASSERT_PARAM.
Referenced by rtdal_process_new().
void pipeline_initialize (int _num_pipelines)
Definition at line 41 of file pipeline.c.
References hdebug, and pipeline_sync_initialize_.
int pipeline_recover_thread (pipeline_t * obj)
Called from the sigwait kernel thread after a pipeline thread has died. Set the process that caused the fault as non-runnable and create a new pipeline thread.
Definition at line 186 of file pipeline.c.
References aerror, pipeline_t::finished, hdebug, pipeline_t::id, kernel_initialize_create_pipeline(), rtdal_process_seterror(), pipeline_t::running_process, and SIG_RECV.
int pipeline_remove (pipeline_t * obj, rtdal_process_t * proc)
Removes the process proc from the pipeline pointed by obj.
Parameters
obj Pointer to the pipeline object
proc Pointer to the process to remove
Returns
Zero on success, -1 on error
Definition at line 286 of file pipeline.c.
References _rtdal_process_t::attributes, rtdal_process_attr::exec_position, pipeline_t::first_process, hdebug, pipeline_t::id, _rtdal_process_t::next, pipeline_t::nof_processes, _rtdal_process_t::pid, RTDAL_ASSERT_PARAM, RTDAL_ERROR_NOTFOUND, and RTDAL_SETERROR.
Referenced by rtdal_process_new(), and rtdal_process_remove().
int pipeline_rt_fault (pipeline_t * obj)
Called when there is an rtfault in the pipeline.
Definition at line 202 of file pipeline.c.
References aerror_msg, pipeline_t::finished, hdebug, pipeline_t::id, pipeline_t::nof_processes, pipeline_t::running_process_idx, pipeline_t::thread, and pipeline_t::ts_counter.
void pipeline_run_from_timer (void * arg, struct timespec * time)
Definition at line 139 of file pipeline.c.
References hdebug, kernel_tslot_run(), rtdal_time_get(), rtdal_time_reset_realtime(), and time_t.
Referenced by kernel_initialize_create_pipeline().
void* pipeline_run_thread (void * self)
Runs one process after another (calling process[i].run_point()) and then sleeps waiting for the semaphore
Definition at line 165 of file pipeline.c.
References hdebug, pipeline_t::id, pipeline_sync_thread_waits, and pipeline_t::stop.
Referenced by kernel_initialize_create_pipeline().
void pipeline_sync_threads () [inline]
Definition at line 47 of file pipeline.c.
References pipeline_sync_threads_wake.