/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_timer.c File Reference
#include <pthread.h>
*
#include <unistd.h>
*
#include <stdlib.h>
*
#include <signal.h>
*
#include <time.h>
*
#include <error.h>
*
#include <sys/timerfd.h>
*
#include `defs.h`
*
#include `rtdal_timer.h`
*
#include `rtdal.h`
*
#include `futex.h`
*
Functions
void timer_close (rtdal_timer_t *info)
int timer_setup (rtdal_timer_t *info)
int timer_start (rtdal_timer_t *info)
int timer_wait_period (rtdal_timer_t *info)
void * timer_run_thread (void *x)
void * timerfd_timer_run_thread (rtdal_timer_t *obj)
void timespec_sub_us (struct timespec *t, long int us)
void * nanoclock_timer_run_thread (rtdal_timer_t *obj)
Function Documentation
void* nanoclock_timer_run_thread (rtdal_timer_t * obj)
Definition at line 177 of file rtdal_timer.c.
References rtdal_timer_t::arg, futex_wait, rtdal_timer_t::next, rtdal_timer_t::period, rtdal_timer_t::period_function, rtdal_timer_t::stop, TIMER_FUTEX_GUARD_SEC, and rtdal_timer_t::wait_futex.
Referenced by timer_run_thread().
void timer_close (rtdal_timer_t * info)
Definition at line 41 of file rtdal_timer.c.
References rtdal_timer_t::timer_fd.
Referenced by timerfd_timer_run_thread().
void* timer_run_thread (void * x)
Definition at line 109 of file rtdal_timer.c.
References aerror_msg, DEBUG_rtdal, rtdal_timer_t::mode, nanoclock_timer_run_thread(), NANOSLEEP, rtdal_task_print_sched(), TIMERFD, and timerfd_timer_run_thread().
Referenced by kernel_initialize_create_pipeline().
int timer_setup (rtdal_timer_t * info)
Definition at line 45 of file rtdal_timer.c.
References aerror_msg, rtdal_timer_t::itval, rtdal_timer_t::period, rtdal_timer_t::timer_fd, and rtdal_timer_t::wakeups_missed.
Referenced by timerfd_timer_run_thread().
int timer_start (rtdal_timer_t * info) [inline]
Definition at line 77 of file rtdal_timer.c.
References rtdal_timer_t::itval, and rtdal_timer_t::timer_fd.
Referenced by timerfd_timer_run_thread().
int timer_wait_period (rtdal_timer_t * info) [inline]
Definition at line 88 of file rtdal_timer.c.
References rtdal_timer_t::timer_fd, and rtdal_timer_t::wakeups_missed.
Referenced by timerfd_timer_run_thread().
void* timerfd_timer_run_thread (rtdal_timer_t * obj)
Definition at line 127 of file rtdal_timer.c.
References aerror, rtdal_timer_t::arg, futex_wait, rtdal_timer_t::period_function, rtdal_timer_t::stop, timer_close(), timer_setup(), timer_start(), timer_wait_period(), and rtdal_timer_t::wait_futex.
Referenced by timer_run_thread().
void timespec_sub_us (struct timespec * t, long int us)
Definition at line 169 of file rtdal_timer.c.