/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_kernel.c File Reference
#include <pthread.h>
*
#include <stdlib.h>
*
#include <stdio.h>
*
#include <signal.h>
*
#include <errno.h>
*
#include <sched.h>
*
#include <unistd.h>
*
#include <sys/types.h>
*
#include <sys/mman.h>
*
#include `rtdal_kernel.h`
*
#include `str.h`
*
#include `defs.h`
*
#include `rtdal_time.h`
*
#include `rtdal_process.h`
*
#include `rtdal_context.h`
*
#include `rtdal_task.h`
*
#include `rtdal.h`
*
#include `rtdal_timer.h`
*
#include `futex.h`
*
Macros
#define KERNEL_SIG_THREAD_SPECIFIC SIGRTMIN
#define N_THREAD_SPECIFIC_SIGNALS 6
Functions
void kernel_tslot_run ()
int kernel_initialize_create_pipeline (pipeline_t *obj, int *wait_futex)
void open_debug_trace ()
void write_debug_trace ()
int parse_cores_comma_sep (char *str)
int parse_cores_single_array (char *core_init, char *core_end)
int parse_cores (char *str)
int main (int argc, char **argv)
Variables
const int thread_specific_signals [N_THREAD_SPECIFIC_SIGNALS]
int * core_mapping
int nof_cores
FILE * trace_buffer = NULL
char * debug_trace_addr
size_t debug_trace_sz
FILE * debug_trace_file
Macro Definition Documentation
#define KERNEL_SIG_THREAD_SPECIFIC SIGRTMIN
Definition at line 40 of file rtdal_kernel.c.
#define N_THREAD_SPECIFIC_SIGNALS 6
Definition at line 41 of file rtdal_kernel.c.
Function Documentation
int kernel_initialize_create_pipeline (pipeline_t * obj, int * wait_futex)
Definition at line 191 of file rtdal_kernel.c.
References rtdal_timer_t::arg, rtdal_machine_t::clock_source, core_mapping, DETACHABLE, hdebug, pipeline_t::id, rtdal_machine_t::kernel_prio, rtdal_context_t::machine, rtdal_timer_t::mode, MULTI_TIMER, pipeline_t::mytimer, NANOSLEEP, rtdal_timer_t::period, rtdal_timer_t::period_function, pipeline_run_from_timer(), pipeline_run_thread(), rtdal_perror, rtdal_task_new_thread(), rtdal_timer_t::thread, pipeline_t::thread, timer_run_thread(), rtdal_machine_t::ts_len_us, and rtdal_timer_t::wait_futex.
Referenced by pipeline_recover_thread().
void kernel_tslot_run () [inline]
Definition at line 119 of file rtdal_kernel.c.
References hdebug, rtdal_time_slot(), and rtdal_time_ts_inc().
Referenced by pipeline_run_from_timer().
int main (int argc, char ** argv)
Definition at line 655 of file rtdal_kernel.c.
References _run_main(), aerror, rtdal_context_t::machine, MULTI_TIMER, rtdal_machine_t::nof_cores, nof_cores, open_debug_trace(), parse_cores(), rtdal_perror, rtdal_task_new(), SINGLE_TIMER, strcmp, and write_debug_trace().
void open_debug_trace ()
Definition at line 542 of file rtdal_kernel.c.
References debug_trace_addr, debug_trace_file, debug_trace_sz, and trace_buffer.
Referenced by main().
int parse_cores (char * str)
Parses a string indicating which cores can be used to load modules Valid string formats are:
`N` Just a number, without `,` nor `:` means to use core id 0 to N-1
`n1:n2` Indicates that core ids n1 to n2 will be used
`n1,n2,n3` Indicates that core ids n1, n2 and n3 only will be used
Definition at line 634 of file rtdal_kernel.c.
References parse_cores_comma_sep(), and parse_cores_single_array().
Referenced by main().
int parse_cores_comma_sep (char * str)
Definition at line 585 of file rtdal_kernel.c.
References core_mapping.
Referenced by parse_cores().
int parse_cores_single_array (char * core_init, char * core_end)
Definition at line 609 of file rtdal_kernel.c.
References core_mapping.
Referenced by parse_cores().
void write_debug_trace ()
Definition at line 553 of file rtdal_kernel.c.
References debug_trace_addr, debug_trace_file, debug_trace_sz, and trace_buffer.
Referenced by main().
Variable Documentation
int* core_mapping
Definition at line 46 of file rtdal_kernel.c.
Referenced by kernel_initialize_create_pipeline(), parse_cores_comma_sep(), parse_cores_single_array(), and rtdal_task_new_thread().
char* debug_trace_addr
Definition at line 66 of file rtdal_kernel.c.
Referenced by open_debug_trace(), and write_debug_trace().
FILE* debug_trace_file
Definition at line 68 of file rtdal_kernel.c.
Referenced by open_debug_trace(), and write_debug_trace().
size_t debug_trace_sz
Definition at line 67 of file rtdal_kernel.c.
Referenced by open_debug_trace(), and write_debug_trace().
int nof_cores
Definition at line 47 of file rtdal_kernel.c.
Referenced by main(), and rtdal_task_new_thread().
const int thread_specific_signals[N_THREAD_SPECIFIC_SIGNALS]
Initial value:
        {SIGSEGV, SIGBUS, SIGILL, SIGFPE, TASK_TERMINATION_SIGNAL
      , SIGUSR1}
Definition at line 42 of file rtdal_kernel.c.
FILE* trace_buffer = NULL
Definition at line 65 of file rtdal_kernel.c.
Referenced by open_debug_trace(), and write_debug_trace().