/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_timer.h File Reference
#include <pthread.h>
*
#include <sys/time.h>
*
#include <time.h>
*
Data Structures
struct rtdal_timer_t
Macros
#define TIMER_FUTEX_GUARD_SEC 2
#define KERNEL_OFFSET_USEC 30
Enumerations
enum timer_mode { NANOSLEEP,
TIMERFD
 }
Functions
void * nanoclock_timer_run_thread (rtdal_timer_t *x)
void * timerfd_timer_run_thread (rtdal_timer_t *x)
void * timer_run_thread (void *timer)
int timer_setup (rtdal_timer_t *timer)
int timer_start (rtdal_timer_t *timer)
int timer_wait_period (rtdal_timer_t *timer)
void timer_close (rtdal_timer_t *timer)
Macro Definition Documentation
#define KERNEL_OFFSET_USEC 30
Definition at line 27 of file rtdal_timer.h.
#define TIMER_FUTEX_GUARD_SEC 2
Definition at line 26 of file rtdal_timer.h.
Referenced by nanoclock_timer_run_thread().
Enumeration Type Documentation
enum timer_mode
Enumerator:
NANOSLEEP
TIMERFD
Definition at line 28 of file rtdal_timer.h.
Function Documentation
void* nanoclock_timer_run_thread (rtdal_timer_t * x)
Definition at line 177 of file rtdal_timer.c.
References rtdal_timer_t::arg, futex_wait, rtdal_timer_t::next, rtdal_timer_t::period, rtdal_timer_t::period_function, rtdal_timer_t::stop, TIMER_FUTEX_GUARD_SEC, and rtdal_timer_t::wait_futex.
Referenced by timer_run_thread().
void timer_close (rtdal_timer_t * timer)
Definition at line 41 of file rtdal_timer.c.
References rtdal_timer_t::timer_fd.
Referenced by timerfd_timer_run_thread().
void* timer_run_thread (void * timer)
Definition at line 109 of file rtdal_timer.c.
References aerror_msg, DEBUG_rtdal, rtdal_timer_t::mode, nanoclock_timer_run_thread(), NANOSLEEP, rtdal_task_print_sched(), TIMERFD, and timerfd_timer_run_thread().
Referenced by kernel_initialize_create_pipeline().
int timer_setup (rtdal_timer_t * timer)
Definition at line 45 of file rtdal_timer.c.
References aerror_msg, rtdal_timer_t::itval, rtdal_timer_t::period, rtdal_timer_t::timer_fd, and rtdal_timer_t::wakeups_missed.
Referenced by timerfd_timer_run_thread().
int timer_start (rtdal_timer_t * timer) [inline]
Definition at line 77 of file rtdal_timer.c.
References rtdal_timer_t::itval, and rtdal_timer_t::timer_fd.
Referenced by timerfd_timer_run_thread().
int timer_wait_period (rtdal_timer_t * timer) [inline]
Definition at line 88 of file rtdal_timer.c.
References rtdal_timer_t::timer_fd, and rtdal_timer_t::wakeups_missed.
Referenced by timerfd_timer_run_thread().
void* timerfd_timer_run_thread (rtdal_timer_t * x)
Definition at line 127 of file rtdal_timer.c.
References aerror, rtdal_timer_t::arg, futex_wait, rtdal_timer_t::period_function, rtdal_timer_t::stop, timer_close(), timer_setup(), timer_start(), timer_wait_period(), and rtdal_timer_t::wait_futex.
Referenced by timer_run_thread().