/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_task.c File Reference
#include <pthread.h>
*
#include <sched.h>
*
#include <unistd.h>
*
#include <signal.h>
*
#include <sys/types.h>
*
#include `defs.h`
*
#include `rtdal_task.h`
*
#include `rtdal.h`
*
#include `rtdal_error.h`
*
#include `rtdal_kernel.h`
*
Functions
int rtdal_task_new (r_task_t *task, void *(*fnc)(void *), void *arg)
int rtdal_task_kill (r_task_t task)
int rtdal_task_wait (r_task_t task, void **retval)
int rtdal_task_wait_nb (r_task_t task, void **retval)
int rtdal_task_new_prio (r_task_t *task, void *(*fnc)(void *), void *arg, int prio, int cpu)
int rtdal_task_new_thread (pthread_t *thread, void *(*fnc)(void *), void *arg, enum rtdal_task_type type, int prio, int cpu, int unblock_signals)
void rtdal_task_print_sched ()
Variables
int * core_mapping
int nof_cores
Function Documentation
int rtdal_task_new_prio (r_task_t * task, void *(*)(void *) fnc, void * arg, int prio, int cpu)
All threads are created with detachable state.
Definition at line 78 of file rtdal_task.c.
References DETACHABLE, JOINABLE, and rtdal_task_new_thread().
Referenced by rtdal_task_new().
int rtdal_task_new_thread (pthread_t * thread, void *(*)(void *) fnc, void * arg, enum rtdal_task_type type, int prio, int cpu, int unblock_signals)
Definition at line 95 of file rtdal_task.c.
References awarn, core_mapping, DETACHABLE, hdebug, nof_cores, RTDAL_ASSERT_PARAM, RTDAL_POSERROR, and TASK_DEFAULT_PRIORITY.
Referenced by kernel_initialize_create_pipeline(), and rtdal_task_new_prio().
Variable Documentation
int* core_mapping
Definition at line 46 of file rtdal_kernel.c.
Referenced by kernel_initialize_create_pipeline(), parse_cores_comma_sep(), parse_cores_single_array(), and rtdal_task_new_thread().
int nof_cores
Definition at line 47 of file rtdal_kernel.c.
Referenced by main(), and rtdal_task_new_thread().