/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_error.c File Reference
#include <stddef.h>
*
#include <stdio.h>
*
#include <errno.h>
*
#include `str.h`
*
#include `rtdal_context.h`
*
#include `rtdal_error.h`
*
#include `rtdal.h`
*
Functions
void rtdal_error_set_context (rtdal_error_t *_context)
void rtdal_error_systemcall (int errnum, const char *file, int line, const char *system_call)
void rtdal_error_set (int code, const char *file, int line)
void rtdal_error_set_msg (int code, const char *file, int line, const char *msg)
void rtdal_error_print (const char *user_message)
string rtdal_error_string ()
int rtdal_error_code ()
Function Documentation
void rtdal_error_set (int code, const char * file, int line)
Definition at line 45 of file rtdal_error.c.
References rtdal_error_set_msg().
void rtdal_error_set_context (rtdal_error_t * _context)
Definition at line 31 of file rtdal_error.c.
Referenced by rtdal_initialize_node().
void rtdal_error_set_msg (int code, const char * file, int line, const char * msg)
Definition at line 49 of file rtdal_error.c.
References rtdal_error_t::code, and LSTR_LEN.
Referenced by rtdal_error_set().
void rtdal_error_systemcall (int errnum, const char * file, int line, const char * system_call)
Definition at line 36 of file rtdal_error.c.
References rtdal_error_t::code, LSTR_LEN, RTDAL_ERROR_SYSTEM, and rtdal_error_t::sys_errnum.