/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_itfspscq.h File Reference
#include `str.h`
*
#include `rtdal_itf.h`
*
#include `rtdal.h`
*
Data Structures
struct r_pkt_t
struct rtdal_itfspscq_t
Functions
int rtdal_itfspscq_init (rtdal_itfspscq_t *obj)
int rtdal_itfspscq_create (r_itf_t obj, string address)
int rtdal_itfspscq_remove (r_itf_t obj)
int rtdal_itfspscq_request (r_itf_t obj, void **ptr)
int rtdal_itfspscq_push (r_itf_t obj, int len)
int rtdal_itfspscq_pop (r_itf_t obj, void **ptr, int *len)
int rtdal_itfspscq_release (r_itf_t obj)
int rtdal_itfspscq_send (r_itf_t obj, void *buffer, int len)
int rtdal_itfspscq_recv (r_itf_t obj, void *buffer, int len)
int rtdal_itfspscq_set_callback (r_itf_t obj, void(*fnc)(void), int prio)
int rtdal_itfspscq_set_blocking (r_itf_t obj, int block)
int rtdal_itfspscq_get_blocking (r_itf_t obj)
int rtdal_itfspscq_set_delay (r_itf_t obj, int delay)
int rtdal_itfspscq_get_delay (r_itf_t obj)
Function Documentation
int rtdal_itfspscq_create (r_itf_t obj, string address)
int rtdal_itfspscq_get_blocking (r_itf_t obj)
Definition at line 180 of file rtdal_itfspscq.c.
References aerror.
int rtdal_itfspscq_get_delay (r_itf_t obj)
Definition at line 164 of file rtdal_itfspscq.c.
References aerror.
int rtdal_itfspscq_init (rtdal_itfspscq_t * obj)
Definition at line 34 of file rtdal_itfspscq.c.
References r_pkt_t::data, rtdal_itfspscq_t::data, rtdal_itf_t::delay, rtdal_itf_t::is_external, rtdal_itfspscq_t::max_msg, rtdal_itfspscq_t::max_msg_sz, rtdal_itfspscq_t::packets, rtdal_itfspscq_t::parent, rtdal_itfspscq_t::read, RTDAL_ASSERT_PARAM, r_pkt_t::valid, and rtdal_itfspscq_t::write.
Referenced by rtdal_itfspscq_new().
int rtdal_itfspscq_pop (r_itf_t obj, void ** ptr, int * len)
Definition at line 117 of file rtdal_itfspscq.c.
References cast, r_pkt_t::data, r_pkt_t::len, rtdal_itfspscq_t::packets, qdebug, rtdal_itfspscq_t::read, RTDAL_ASSERT_PARAM, rtdal_time_slot(), and r_pkt_t::tstamp.
Referenced by rtdal_itfspscq_recv().
int rtdal_itfspscq_push (r_itf_t obj, int len)
Definition at line 101 of file rtdal_itfspscq.c.
References cast, rtdal_itf_t::delay, r_pkt_t::len, rtdal_itfspscq_t::max_msg, rtdal_itfspscq_t::packets, rtdal_itfspscq_t::parent, qdebug, RTDAL_ERROR_NOSPACE, RTDAL_SETERROR, rtdal_time_slot(), r_pkt_t::tstamp, r_pkt_t::valid, and rtdal_itfspscq_t::write.
Referenced by rtdal_itfspscq_send().
int rtdal_itfspscq_recv (r_itf_t obj, void * buffer, int len)
Definition at line 210 of file rtdal_itfspscq.c.
References cast, hdebug, RTDAL_ASSERT_PARAM, rtdal_itfspscq_pop(), and rtdal_itfspscq_release().
int rtdal_itfspscq_release (r_itf_t obj)
Definition at line 145 of file rtdal_itfspscq.c.
References cast, rtdal_itfspscq_t::max_msg, rtdal_itfspscq_t::packets, qdebug, rtdal_itfspscq_t::read, r_pkt_t::tstamp, and r_pkt_t::valid.
Referenced by rtdal_itfspscq_recv().
int rtdal_itfspscq_remove (r_itf_t obj)
Definition at line 56 of file rtdal_itfspscq.c.
References cast.
int rtdal_itfspscq_request (r_itf_t obj, void ** ptr)
Definition at line 82 of file rtdal_itfspscq.c.
References cast, r_pkt_t::data, rtdal_itfspscq_t::max_msg, rtdal_itfspscq_t::packets, qdebug, RTDAL_ASSERT_PARAM, RTDAL_ERROR_NOSPACE, RTDAL_SETERROR, r_pkt_t::tstamp, and rtdal_itfspscq_t::write.
Referenced by rtdal_itfspscq_send().
int rtdal_itfspscq_send (r_itf_t obj, void * buffer, int len)
Definition at line 186 of file rtdal_itfspscq.c.
References cast, hdebug, rtdal_itfspscq_t::max_msg_sz, RTDAL_ASSERT_PARAM, RTDAL_ERROR_LARGE, rtdal_itfspscq_push(), rtdal_itfspscq_request(), and RTDAL_SETERROR.
int rtdal_itfspscq_set_blocking (r_itf_t obj, int block)
Definition at line 175 of file rtdal_itfspscq.c.
References aerror.
int rtdal_itfspscq_set_callback (r_itf_t obj, void(*)(void) fnc, int prio)
Definition at line 170 of file rtdal_itfspscq.c.
References aerror.
int rtdal_itfspscq_set_delay (r_itf_t obj, int delay)
Definition at line 159 of file rtdal_itfspscq.c.
References aerror.