/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_time.c File Reference
#include <time.h>
*
#include <sys/time.h>
*
#include <errno.h>
*
#include `defs.h`
*
#include `rtdal_time.h`
*
#include `rtdal.h`
*
#include `rtdal_error.h`
*
Functions
void rtdal_time_set_context (rtdal_time_t *_context)
int rtdal_time_reset ()
int rtdal_time_reset_realtime (struct timespec *x)
void rtdal_time_ts_inc ()
int rtdal_time_set (time_t *time)
int rtdal_time_get (time_t *time)
int rtdal_time_slot ()
void rtdal_time_interval (time_t *tdata)
int rtdal_time_to_tstamp (time_t *tdata)
void tstamp_to_time (int tstamp, time_t *tdata)
int rtdal_time_attach_local ()
Function Documentation
int rtdal_time_reset ()
Definition at line 40 of file rtdal_time.c.
References rtdal_time_t::init_time, RTDAL_SYSERROR, and rtdal_time_t::ts_counter.
Referenced by rtdal_initialize_node().
int rtdal_time_reset_realtime (struct timespec * x)
Definition at line 56 of file rtdal_time.c.
References rtdal_time_t::init_time, and rtdal_time_t::ts_counter.
Referenced by pipeline_run_from_timer().
void rtdal_time_set_context (rtdal_time_t * _context)
Sets the rtdal context pointer
Parameters
_context
Definition at line 35 of file rtdal_time.c.
Referenced by rtdal_initialize_node().
int rtdal_time_to_tstamp (time_t * tdata)
Converts a given time to the equivalent timestamp, given the current slot length
Parameters
tdata
Returns
Definition at line 144 of file rtdal_time.c.
References RTDAL_ASSERT_PARAM, and rtdal_time_t::ts_len_us.
void rtdal_time_ts_inc () [inline]
Definition at line 65 of file rtdal_time.c.
References rtdal_time_t::ts_counter.
Referenced by kernel_tslot_run().
void tstamp_to_time (int tstamp, time_t * tdata)
Converts a timestamp to the equivalent time at its origin, given the platform timeslot length
Parameters
tstamp
tdata
Definition at line 160 of file rtdal_time.c.
References rtdal_time_t::ts_len_us.