rtdal_context_t Struct Reference
#include <rtdal_context.h>
Data Fields
rtdal_error_t error
rtdal_machine_t machine
rtdal_time_t time
rtdal_itfspscq_t spscqs [MAX(rtdal_itfspscq)]
rtdal_periodic_t periodic [MAX(rtdal_periodic)]
int nof_periodic
pipeline_t pipelines [MAX(pipeline)]
rtdal_process_t processes [MAX(rtdal_process)]
rtdal_dac_t dacs [MAX(rtdal_dac)]
rtdal_itfphysic_t physic_itfs [MAX(rtdal_itfphysic)]
int wake_tslot
pthread_mutex_t mutex
Detailed Description
The Base rtdal class abstracts the platform (OS) and hardware particularities, for instance: timers, shared memory, physical interfaces and process creation/scheduling.
Only one instance of this class can be created on each node. This is created by the kernel-thread class at boot of every node or by the Manager process. The rtdal is in charge of controlling thread-local-storage. Therefore, there is no need to pass a pointer to the rtdal context to each function call. In linux, can be implemented using POSIX TLS or __thread GCC. However, this is not strictly required since only one execution thread access thread-sensible functions at a time.
Definition at line 40 of file rtdal_context.h.
Field Documentation
rtdal_dac_t rtdal_context_t::dacs[MAX(rtdal_dac)]
Definition at line 49 of file rtdal_context.h.
rtdal_error_t rtdal_context_t::error
Definition at line 41 of file rtdal_context.h.
Referenced by rtdal_initialize_node().
rtdal_machine_t rtdal_context_t::machine
Definition at line 42 of file rtdal_context.h.
Referenced by kernel_initialize_create_pipeline(), main(), rtdal_initialize_node(), and rtdal_machine().
pthread_mutex_t rtdal_context_t::mutex
Definition at line 52 of file rtdal_context.h.
Referenced by rtdal_itfspscq_new(), rtdal_periodic_add(), rtdal_periodic_remove(), and rtdal_process_new().
int rtdal_context_t::nof_periodic
Definition at line 46 of file rtdal_context.h.
rtdal_periodic_t rtdal_context_t::periodic[MAX(rtdal_periodic)]
Definition at line 45 of file rtdal_context.h.
Referenced by rtdal_periodic_add(), and rtdal_periodic_remove().
rtdal_itfphysic_t rtdal_context_t::physic_itfs[MAX(rtdal_itfphysic)]
Definition at line 50 of file rtdal_context.h.
Referenced by rtdal_itfphysic_get(), and rtdal_itfphysic_get_id().
pipeline_t rtdal_context_t::pipelines[MAX(pipeline)]
Definition at line 47 of file rtdal_context.h.
Referenced by rtdal_process_new().
rtdal_process_t rtdal_context_t::processes[MAX(rtdal_process)]
Definition at line 48 of file rtdal_context.h.
Referenced by rtdal_process_new().
rtdal_itfspscq_t rtdal_context_t::spscqs[MAX(rtdal_itfspscq)]
Definition at line 44 of file rtdal_context.h.
Referenced by rtdal_itfspscq_new().
rtdal_time_t rtdal_context_t::time
Definition at line 43 of file rtdal_context.h.
Referenced by rtdal_initialize_node().
int rtdal_context_t::wake_tslot
Definition at line 51 of file rtdal_context.h.
The documentation for this struct was generated from the following file:
/home/ismael/aloe_ws/aloe_git/rtdal_lnx/src/rtdal_context.h